baseurl = "/"
languageCode = "ru-ru"
title = "Юрий Литвиненко"
theme = "hugo-strata-theme"
#disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Юрий Литвиненко"
	description = "Agile коучинг, обучение, консультирование"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = ["css/custom.css"]


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Юрий Литвиненко**<div>Agile Coach, тренер, консультант</div>"
		# The icons will be shown if you enter your username
		twitter = "yurylyt"
		github = "surg"
#		gitlab = "spf13"
#		dribbble = ""
		facebook = "yuriy.litvinenko"
#		googleplus = ""
#		flickr = ""
		linkedin = "lytvynenko"

		copyright = [
			"&copy; Юрий Литвиненко",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Привет! Меня зовут Юра Литвиненко. <br>Я – Agile Coach с сильным бекграундом в разработке софта."
		content = ["Я помогаю людям и организациям разобраться что такое Agile, как это работает, какие есть инструменты и как с их помощью делать работу лучше, качественнее и быстрее. Умею объяснить сложное просто. Научить, помочь начать использовать, посоветовать. ",

		"В моем арсенале  - Scrum, Kanban, Lean Startup и многое другое. <br>Методы работы - обучение, консультирование, командный коучинг, персональный коучинг и менторство.<br>В основном работаю с IT компаниями и командами, есть опыт и с другими областями. ",
		"С Agile познакомился в 2011 году, с тех пор активно применяю на практике.",
         "Иногда пишу в [блог](https://medium.com/@yurylytvynenko). Часто выступаю на конференциях. "]


	[params.portfolio]
		hide  = true

	[params.recentposts]
		hide  = true
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Напишите мне"
#		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		# This can be exact coordinates or a searchable address in google maps
#		gmaps_address = "39.7889055,-120.5443524"
		address = [
			"Харьков, Украина"
		]
		phone = "+380.93.448.48.24"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "inbox@yury-lytvynenko.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Имя"
			email = "Email"
			message = "Сообщение"
			submit = "Отправить"
        [params.rss]
            hide = true


# Menu links that appear on the left sidebar
#[[menu.main]]
#	name = "Home"
#	url  = "/"
#	weight = 10

[[menu.main]]
	name = "Blog"
	url  = "https://medium.com/@yurylytvynenko"
	weight = 0
